-- MySQL Script generated by MySQL Workbench
-- Wed Sep 20 18:47:42 2023
-- Model: Virtuajoint Model    Version: 1.0

-- Modelo del sistema VirtuaJoint

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema virtuajoint
-- -----------------------------------------------------
-- Modelo simplificado de Virtuajoint, solo incluyendo las tablas completamente necesarias para comenzar a insertar registros de los carritos que tengo

-- -----------------------------------------------------
-- Schema virtuajoint
--
-- Modelo simplificado de Virtuajoint, solo incluyendo las tablas completamente necesarias para comenzar a insertar registros de los carritos que tengo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `virtuajoint` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `virtuajoint` ;

-- -----------------------------------------------------
-- Table `virtuajoint`.`Colores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuajoint`.`Colores` (
  `idColores` INT NOT NULL AUTO_INCREMENT,
  `nombreColor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idColores`),
  UNIQUE INDEX `idColores_UNIQUE` (`idColores` ASC) VISIBLE,
  UNIQUE INDEX `nombreColor_UNIQUE` (`nombreColor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuajoint`.`LugaresCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuajoint`.`LugaresCompra` (
  `idlugaresCompra` INT NOT NULL AUTO_INCREMENT,
  `nombreLugarCompra` VARCHAR(45) NULL,
  PRIMARY KEY (`idlugaresCompra`),
  UNIQUE INDEX `idlugaresCompra_UNIQUE` (`idlugaresCompra` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuajoint`.`TipoMarca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuajoint`.`TipoMarca` (
  `idTipoMarca` INT NOT NULL,
  `nombreTipoMarca` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuajoint`.`Paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuajoint`.`Paises` (
  `idPaises` INT NOT NULL AUTO_INCREMENT,
  `nombrePaises` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPaises`),
  UNIQUE INDEX `idPaises_UNIQUE` (`idPaises` ASC) VISIBLE,
  UNIQUE INDEX `nombrePaises_UNIQUE` (`nombrePaises` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuajoint`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuajoint`.`Marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `nombreMarca` VARCHAR(45) NOT NULL,
  `idTipoMarca` INT NOT NULL,
  `idPais` INT NOT NULL,
  `fundacion` SMALLINT(5) NULL COMMENT 'Año de fundación de la marca',
  PRIMARY KEY (`idMarca`, `idTipoMarca`, `idPais`),
  UNIQUE INDEX `nombreMarca_UNIQUE` (`nombreMarca` ASC) VISIBLE,
  UNIQUE INDEX `idMarca_UNIQUE` (`idMarca` ASC) VISIBLE,
  INDEX `FK-Marca-Tipo_idx` (`idTipoMarca` ASC) VISIBLE,
  INDEX `FK_Marca-Pais_idx` (`idPais` ASC) VISIBLE,
  CONSTRAINT `FK-Marca-Tipo`
    FOREIGN KEY (`idTipoMarca`)
    REFERENCES `virtuajoint`.`TipoMarca` (`idTipoMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Marca-Pais`
    FOREIGN KEY (`idPais`)
    REFERENCES `virtuajoint`.`Paises` (`idPaises`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuajoint`.`Modelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuajoint`.`Modelos` (
  `idModelos` INT NOT NULL AUTO_INCREMENT,
  `nombreModelo` VARCHAR(45) NOT NULL,
  `añoModelo` VARCHAR(45) NULL COMMENT 'Todos los registros con 1901 en el año del modelo, es por que están pendientes de definirse el año real',
  `idMarcaJuguetera` INT NOT NULL,
  `idMarcaArmadora` INT NOT NULL,
  PRIMARY KEY (`idModelos`, `idMarcaJuguetera`, `idMarcaArmadora`),
  UNIQUE INDEX `idModelos_UNIQUE` (`idModelos` ASC) VISIBLE,
  CONSTRAINT `FK_Modelos-Marca`
    FOREIGN KEY (`idMarcaJuguetera`)
    REFERENCES `virtuajoint`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuajoint`.`Autos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuajoint`.`Autos` (
  `idAutos` INT NOT NULL AUTO_INCREMENT,
  `fechaCompra` DATE NOT NULL DEFAULT '1990-02-19',
  `precioCompra` DECIMAL(5,2) NOT NULL DEFAULT 0.0,
  `idLugarCompra` INT NOT NULL,
  `idModeloAuto` INT NOT NULL,
  PRIMARY KEY (`idAutos`, `idLugarCompra`, `idModeloAuto`),
  UNIQUE INDEX `idAutos_UNIQUE` (`idAutos` ASC) VISIBLE,
  INDEX `FK_Autos-Lugar_idx` (`idLugarCompra` ASC) VISIBLE,
  INDEX `FK_Autos-Modelo_idx` (`idModeloAuto` ASC) VISIBLE,
  CONSTRAINT `FK_Autos-Lugar`
    FOREIGN KEY (`idLugarCompra`)
    REFERENCES `virtuajoint`.`LugaresCompra` (`idlugaresCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Autos-Modelo`
    FOREIGN KEY (`idModeloAuto`)
    REFERENCES `virtuajoint`.`Modelos` (`idModelos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuajoint`.`ColoresPorAuto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuajoint`.`ColoresPorAuto` (
  `idColoresPorAuto` INT NOT NULL AUTO_INCREMENT,
  `colorCarroceriaPrincipal` INT NOT NULL,
  `colorCarroceriaSecundario` INT NULL,
  `colorCarroceriaTerciario` INT NULL,
  `colorBase` INT NULL,
  `colorInteriores` INT NULL,
  `colorVidrios` INT NULL,
  `idAuto` INT NOT NULL,
  UNIQUE INDEX `idColoresPorAuto_UNIQUE` (`idColoresPorAuto` ASC) VISIBLE,
  PRIMARY KEY (`idColoresPorAuto`, `colorCarroceriaPrincipal`, `idAuto`),
  INDEX `FK_Colores_idx` (`colorCarroceriaPrincipal` ASC) VISIBLE,
  UNIQUE INDEX `idAuto_UNIQUE` (`idAuto` ASC) VISIBLE,
  CONSTRAINT `FK_ColoresXA-Colores`
    FOREIGN KEY (`colorCarroceriaPrincipal`)
    REFERENCES `virtuajoint`.`Colores` (`idColores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ColoresXAuto-Autos`
    FOREIGN KEY (`idAuto`)
    REFERENCES `virtuajoint`.`Autos` (`idAutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `virtuajoint`.`Colores`
-- -----------------------------------------------------
START TRANSACTION;
USE `virtuajoint`;
INSERT INTO `virtuajoint`.`Colores` (`idColores`, `nombreColor`) VALUES (1, 'Amarillo');
INSERT INTO `virtuajoint`.`Colores` (`idColores`, `nombreColor`) VALUES (2, 'Anaranjado');
INSERT INTO `virtuajoint`.`Colores` (`idColores`, `nombreColor`) VALUES (3, 'Azul');
INSERT INTO `virtuajoint`.`Colores` (`idColores`, `nombreColor`) VALUES (4, 'Beige');
INSERT INTO `virtuajoint`.`Colores` (`idColores`, `nombreColor`) VALUES (5, 'Blanco');
INSERT INTO `virtuajoint`.`Colores` (`idColores`, `nombreColor`) VALUES (6, 'Café');
INSERT INTO `virtuajoint`.`Colores` (`idColores`, `nombreColor`) VALUES (7, 'Dorado');
INSERT INTO `virtuajoint`.`Colores` (`idColores`, `nombreColor`) VALUES (8, 'Gris');
INSERT INTO `virtuajoint`.`Colores` (`idColores`, `nombreColor`) VALUES (9, 'Morado');
INSERT INTO `virtuajoint`.`Colores` (`idColores`, `nombreColor`) VALUES (10, 'Negro');
INSERT INTO `virtuajoint`.`Colores` (`idColores`, `nombreColor`) VALUES (11, 'Plateado');
INSERT INTO `virtuajoint`.`Colores` (`idColores`, `nombreColor`) VALUES (12, 'Rojo');
INSERT INTO `virtuajoint`.`Colores` (`idColores`, `nombreColor`) VALUES (13, 'Verde');
INSERT INTO `virtuajoint`.`Colores` (`idColores`, `nombreColor`) VALUES (14, 'NA');
INSERT INTO `virtuajoint`.`Colores` (`idColores`, `nombreColor`) VALUES (0, 'Pendiente');

COMMIT;


-- -----------------------------------------------------
-- Data for table `virtuajoint`.`LugaresCompra`
-- -----------------------------------------------------
START TRANSACTION;
USE `virtuajoint`;
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (1, 'Aurrera Esmeralda San Alfonso');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (2, 'Aurrera La Viga');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (3, 'Aurrera Matilde, Pachuca');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (4, 'Aurrera Viaducto');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (5, 'Beto Superwheels');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (6, 'Chedraui Universidad');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (7, 'Comercial Mexicana Chabacano');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (8, 'Coppel Viaducto');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (9, 'Desconocido');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (10, 'Jamaica');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (11, 'Juguetibici Las Antenas');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (12, 'Leobas Shop');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (13, 'Liverpool Parque Delta');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (14, 'Liverpool Santa Fé');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (15, 'Mega Soriana Asturias');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (16, 'Mega Soriana Coapa');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (17, 'Mercado Ortíz Tirado');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (18, 'Papeleria Veracruz');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (19, 'Puesto de Coyuya');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (20, 'Puesto de Francisco Daniel en Coruña');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (21, 'Puesto de Insurgentes');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (22, 'Puesto de Jamaica');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (23, 'Regalo de Jeannette');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (24, 'Soriana Asturias');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (25, 'Soriana Coapa');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (26, 'Soriana El Retoño');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (27, 'Soriana Parque Delta');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (28, 'Tianguis Juguetes Alameda');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (29, 'Walmart Azcapotzalco');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (30, 'Walmart Boturini');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (31, 'Walmart miramontes');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (32, 'Walmart Miramontes');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (33, 'Walmart Nativitas');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (34, 'Walmart Periferico Sur');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (35, 'Walmart Portal Centro');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (36, 'Walmart Taxqueña');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (37, 'Walmart Universidad');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (38, 'Walmart Villacoapa');

COMMIT;


-- -----------------------------------------------------
-- Data for table `virtuajoint`.`TipoMarca`
-- -----------------------------------------------------
START TRANSACTION;
USE `virtuajoint`;
INSERT INTO `virtuajoint`.`TipoMarca` (`idTipoMarca`, `nombreTipoMarca`) VALUES (1, 'Armadora');
INSERT INTO `virtuajoint`.`TipoMarca` (`idTipoMarca`, `nombreTipoMarca`) VALUES (2, 'Juguetera');
INSERT INTO `virtuajoint`.`TipoMarca` (`idTipoMarca`, `nombreTipoMarca`) VALUES (0, 'Pendiente');

COMMIT;


-- -----------------------------------------------------
-- Data for table `virtuajoint`.`Paises`
-- -----------------------------------------------------
START TRANSACTION;
USE `virtuajoint`;
INSERT INTO `virtuajoint`.`Paises` (`idPaises`, `nombrePaises`) VALUES (1, 'Alemania');
INSERT INTO `virtuajoint`.`Paises` (`idPaises`, `nombrePaises`) VALUES (2, 'Corea Sur');
INSERT INTO `virtuajoint`.`Paises` (`idPaises`, `nombrePaises`) VALUES (3, 'EUA');
INSERT INTO `virtuajoint`.`Paises` (`idPaises`, `nombrePaises`) VALUES (4, 'Francia');
INSERT INTO `virtuajoint`.`Paises` (`idPaises`, `nombrePaises`) VALUES (5, 'Inglaterra');
INSERT INTO `virtuajoint`.`Paises` (`idPaises`, `nombrePaises`) VALUES (6, 'Italia');
INSERT INTO `virtuajoint`.`Paises` (`idPaises`, `nombrePaises`) VALUES (7, 'Japon');
INSERT INTO `virtuajoint`.`Paises` (`idPaises`, `nombrePaises`) VALUES (8, 'Suecia');
INSERT INTO `virtuajoint`.`Paises` (`idPaises`, `nombrePaises`) VALUES (9, 'China');
INSERT INTO `virtuajoint`.`Paises` (`idPaises`, `nombrePaises`) VALUES (10, 'Indonesia');
INSERT INTO `virtuajoint`.`Paises` (`idPaises`, `nombrePaises`) VALUES (11, 'Malasia');
INSERT INTO `virtuajoint`.`Paises` (`idPaises`, `nombrePaises`) VALUES (12, 'Tailandia');
INSERT INTO `virtuajoint`.`Paises` (`idPaises`, `nombrePaises`) VALUES (13, 'Mexico');
INSERT INTO `virtuajoint`.`Paises` (`idPaises`, `nombrePaises`) VALUES (0, 'Pendiente');

COMMIT;


-- -----------------------------------------------------
-- Data for table `virtuajoint`.`Marca`
-- -----------------------------------------------------
START TRANSACTION;
USE `virtuajoint`;
INSERT INTO `virtuajoint`.`Marca` (`idMarca`, `nombreMarca`, `idTipoMarca`, `idPais`, `fundacion`) VALUES (1, 'Bburago ', 2, 6, 1976);
INSERT INTO `virtuajoint`.`Marca` (`idMarca`, `nombreMarca`, `idTipoMarca`, `idPais`, `fundacion`) VALUES (2, 'HotWheels ', 2, 3, 1968);
INSERT INTO `virtuajoint`.`Marca` (`idMarca`, `nombreMarca`, `idTipoMarca`, `idPais`, `fundacion`) VALUES (3, 'Maisto', 2, 9, 1967);
INSERT INTO `virtuajoint`.`Marca` (`idMarca`, `nombreMarca`, `idTipoMarca`, `idPais`, `fundacion`) VALUES (4, 'Majorette', 2, 4, 1961);
INSERT INTO `virtuajoint`.`Marca` (`idMarca`, `nombreMarca`, `idTipoMarca`, `idPais`, `fundacion`) VALUES (5, 'MatchBox', 2, 5, 1953);
INSERT INTO `virtuajoint`.`Marca` (`idMarca`, `nombreMarca`, `idTipoMarca`, `idPais`, `fundacion`) VALUES (6, 'Welly', 2, 9, 1979);
INSERT INTO `virtuajoint`.`Marca` (`idMarca`, `nombreMarca`, `idTipoMarca`, `idPais`, `fundacion`) VALUES (0, 'Pendiente', 0, 0, 0000);

COMMIT;


-- -----------------------------------------------------
-- Data for table `virtuajoint`.`Modelos`
-- -----------------------------------------------------
START TRANSACTION;
USE `virtuajoint`;
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (1, '934.5', '2016', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (2, '2 Jet Z', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (3, '240 Drift Wagon', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (4, '356B Convertible', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (5, '370Z', '2010', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (6, '5 Alarm', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (7, '599XX', '2009', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (8, '718 Boxster', '2016', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (9, '8C Competizione', '2007', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (10, '911 GT-2', '2010', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (11, '911 Rally', '1985', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (12, '917LH', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (13, '918 Spyder', '2013', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (14, 'Acre Maker', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (15, 'Airuption', '2022', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (16, 'Alpine A110', '2017', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (17, 'AMG GT', '2014', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (18, 'Aristo Rat', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (19, 'Aventador J', '2012', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (20, 'Baja Bandit', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (21, 'Baja Bone Shaker', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (22, 'Ballistik', '2002', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (23, 'Barracuda Formula S', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (24, 'Beat All', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (25, 'Bel Air', '1957', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (26, 'Bentayga', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (27, 'Blastous Moto', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (28, 'Bogzilla', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (29, 'Bot Wheels', '2018', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (30, 'Bricking Speed', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (31, 'Bricking Trails', '2022', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (32, 'Bronco', '2021', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (33, 'Bump Around', '2017', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (34, 'C4 Cactus', '2018', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (35, 'Camaro', '1981', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (36, 'Camaro Custom', '2011', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (37, 'Camaro SS', '2016', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (38, 'Carbonator', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (39, 'Carrera GT', '2003', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (40, 'Charger', '1969', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (41, 'Charger', '1971', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (42, 'Chevelle SS 396 \'67', '1967', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (43, 'Chevy Nova \'66', '1966', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (44, 'Chiron', '2016', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (45, 'Chow Mobile', '2014', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (46, 'City Turbo II', '1985', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (47, 'Civic Custom', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (48, 'Civic EF', '1990', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (49, 'Classic 55 Nomad', '1955', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (50, 'Clear Speeder', '2021', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (51, 'Cliff Hanger', '2010', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (52, 'Cloud Cutter', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (53, 'Cobra 427 S/C', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (54, 'Colorado Xtreme', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (55, 'Continental', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (56, 'Corvette', '1955', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (57, 'Corvette C6R', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (58, 'Corvette C7 Z06', '2016', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (59, 'Corvette C7 Z06 Convertible', '2017', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (60, 'Corvette C7.R', '2014', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (61, 'Corvette Gasser', '1962', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (62, 'Corvette Racer', '1969', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (63, 'Corvette Stingray', '2014', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (64, 'Cosmic Coupe', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (65, 'Count Muscula', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (66, 'Crop Master', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (67, 'CR-X', '1985', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (68, 'CR-X', '1988', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (69, 'CTS Coupe', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (70, 'Custom \'18 Mustang GT', '2018', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (71, 'Custom Datsun 240Z', '1973', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (72, 'Custom Small Block', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (73, 'CX-5', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (74, 'Cybertruck', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (75, 'Darth Vader', '2014', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (76, 'DAVancenator', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (77, 'DB10', '2014', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (78, 'DB5', '1963', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (79, 'DBS', '2010', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (80, 'Deora III', '2018', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (81, 'Diaper Dragger', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (82, 'Dimachinni Veloce', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (83, 'Dino 246 GTS', '1968', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (84, 'Draggin Tail', '2009', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (85, 'Dragster', '1994', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (86, 'Dune Crusher', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (87, 'Dune-A-Soar', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (88, 'Eevil Weevil', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (89, 'El Camino 71', '1971', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (90, 'Electro Silhouette', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (91, 'Escort RS1600', '1970', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (92, 'Esprit S1', '1976', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (93, 'Express Delivery', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (94, 'F1', '1992', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (95, 'F1 GT3', '1995', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (96, 'F1 GTR', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (97, 'F-100', '1956', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (98, 'F-150 SVT Raptor', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (99, 'Firebird', '1970', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (100, 'Firebird', '1984', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (101, 'Four X Force', '2015', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (102, 'F-Type', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (103, 'Geoterra', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (104, 'GLE Coupe', '2015', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (105, 'Glory Chaser', '2022', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (106, 'GT LM', '2005', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (107, 'GTO', '2006', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (108, 'GT-R (R35) - Guaczilla', '2017', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (109, 'GTR R35', '2017', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (110, 'Haulin\' Class', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (111, 'Haul-O-Gram', '2019', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (112, 'Head Gasket', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (113, 'Honda CR-X', '1988', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (114, 'Hot Wired', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (115, 'HotWheels Transit Connect', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (116, 'Huayra', '2012', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (117, 'Huracan LP 610-4', '2014', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (118, 'Hyper Rocker', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (119, 'Indy 500 Oval', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (120, 'Iridium', '2014', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (121, 'Jay Leno Tank Car', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (122, 'Justice League Batmobile', '2017', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (123, 'Kadett', '1975', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (124, 'Kanan', '2014', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (125, 'Knight Draggin\'', '2020', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (126, 'L200 Triton', '2008', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (127, 'Land Rover Defender 110', '1997', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (128, 'Land Shark', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (129, 'LB Super Silhouette Silvia (S15)', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (130, 'LB-Silhouette WORKS GT 35GT-RR VER.2', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (131, 'Let\'s Go', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (132, 'Lightnin\' Bug', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (133, 'LM002', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (134, 'Load Lifter', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (135, 'Luke Skywalker', '2014', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (136, 'Mario Standard Kart', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (137, 'Matt and Debbie Hay\'s Pro Street Thunderbird', '1988', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (138, 'MBX 4X4', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (139, 'MBX Armored Truck', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (140, 'MBX Mini Swisher', '2018', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (141, 'Meter Made', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (142, 'MGB Coupe', '1971', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (143, 'MGB GT Coupe', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (144, 'Mini Cooper', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (145, 'Model 3', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (146, 'Model S', '2012', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (147, 'MR2', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (148, 'Mustang', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (149, 'Mustang 2+2 Fastback', '1965', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (150, 'Mustang Convertible', '2018', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (151, 'Mustang GT', '2018', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (152, 'Mustang GT Concept', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (153, 'Mustang Mach-E 1400', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (154, 'MX-5 Miata', '2015', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (155, 'MX-5 Miata', '1991', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (156, 'MXR', '2013', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (157, 'NSX Concept', '2012', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (158, 'Octane', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (159, 'Off Road Rider', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (160, 'Ollie Rocket', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (161, 'P1', '2013', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (162, 'Pajero Evolution', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (163, 'Panamera', '2013', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (164, 'Panamera Turbo S E-Hybrid Spor Turismo', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (165, 'PickUp', '1940', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (166, 'Piranha Terror', '2019', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (167, 'Power Pistons', '1994', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (168, 'Push \'N Puller', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (169, 'Quarry King', '2007', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (170, 'R390 GT1', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (171, 'R8', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (172, 'Rally Truck', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (173, 'Range Rover Classic', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (174, 'Range Rover Evoque', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (175, 'Ranger Raptor', '2019', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (176, 'Rat Rig', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (177, 'RD-03', '2014', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (178, 'Red Planet Transport', '2021', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (179, 'Reventon Roadster', '2007', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (180, 'Rising Heat', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (181, 'Road Mauler', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (182, 'Roller Toaster', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (183, 'RS 6 Avant', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (184, 'RS2 Avant', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (186, 'RX-7 \'95', '1995', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (187, 'RZR', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (188, 'S2000', '2011', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (189, 'Savanna RX-7 FC3S', '1989', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (190, 'SC400', '1990', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (191, 'Sea Hunter', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (192, 'Series III PickUp', '1971', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (193, 'Sesto Elemento', '2010', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (194, 'Shelby GT500', '2010', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (195, 'Silverado Trail Boss LT', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (196, 'Skidster', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (197, 'Skull Shaker', '2019', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (198, 'Skull Shaker', '2018', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (199, 'Skyline 2000 GT-R', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (200, 'Skyline 2000 GTX', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (201, 'Skyline GT-R (BNR32)', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (202, 'Slingshot', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (203, 'SLS', '2010', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (204, 'Snow Ripper', '2016', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (205, 'Snow Stormer', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (206, 'Sooo Fast', '2000', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (207, 'SP2', '1972', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (208, 'Spark Arrestor', '2014', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (209, 'Speed Trap', '2020', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (210, 'Sport Quattro', '1984', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (211, 'Sport RS', '2010', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (212, 'Street Wiener', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (213, 'Swamp Commander', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (214, 'Swat Truck', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (215, 'Sweet Driver', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (216, 'Sweptside Pickup', '1957', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (217, 'Symbolic', '2020', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (218, 'Terrain Trouncer', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (219, 'Terzo Millennio', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (220, 'TGS Dump truck 18.440', '2018', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (221, 'The Dark Knight Batmobile', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (222, 'Tomb Up', '2019', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (223, 'Turbine Sublime', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (224, 'V12 Speedster', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (225, 'V60', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (226, 'Valhalla Concept', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (227, 'Van', '1986', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (228, 'Vantom', '2012', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (229, 'Veloci-Racer', '1901', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (230, 'Viper RT/10', '1992', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (231, 'Vulcan', '2015', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (232, 'What-4-2', '2020', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (233, 'Wicket', '2014', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (234, 'Willys Pickup 4x4', '1962', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (235, 'Wrangler', '2017', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (236, 'WRX STI', '2015', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (237, 'XE SV Project 8', '2017', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (238, 'XJ220', '1992', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (239, 'X-Wing Fighter', '2016', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (240, 'Yoda', '2014', 0, 0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcaArmadora`) VALUES (241, 'Z Proto', '1901', 0, 0);

COMMIT;

