-- MySQL Script generated by MySQL Workbench
-- Mon Aug  7 17:36:26 2023
-- Model: Virtuajoint Model    Version: 1.0

-- Modelo del sistema VirtuaJoint

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema virtuajoint
-- -----------------------------------------------------
-- Modelo simplificado de Virtuajoint, solo incluyendo las tablas completamente necesarias para comenzar a insertar registros de los carritos que tengo

-- -----------------------------------------------------
-- Schema virtuajoint
--
-- Modelo simplificado de Virtuajoint, solo incluyendo las tablas completamente necesarias para comenzar a insertar registros de los carritos que tengo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `virtuajoint` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `virtuajoint` ;

-- -----------------------------------------------------
-- Table `virtuajoint`.`Colores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuajoint`.`Colores` (
  `idColores` INT NOT NULL AUTO_INCREMENT,
  `nombreColor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idColores`),
  UNIQUE INDEX `idColores_UNIQUE` (`idColores` ASC) VISIBLE,
  UNIQUE INDEX `nombreColor_UNIQUE` (`nombreColor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuajoint`.`ColoresPorAuto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuajoint`.`ColoresPorAuto` (
  `idColoresPorAuto` INT NOT NULL AUTO_INCREMENT,
  `colorCarroceriaPrincipal` INT NOT NULL,
  `colorCarroceriaSecundario` INT NULL,
  `colorCarroceriaTerciario` INT NULL,
  `colorBase` INT NULL,
  `colorInteriores` INT NULL,
  `colorVidrios` INT NULL,
  UNIQUE INDEX `idColoresPorAuto_UNIQUE` (`idColoresPorAuto` ASC) VISIBLE,
  PRIMARY KEY (`idColoresPorAuto`, `colorCarroceriaPrincipal`),
  INDEX `FK_Colores_idx` (`colorCarroceriaPrincipal` ASC) VISIBLE,
  INDEX `FK_ColoresXA-Sec_idx` (`colorCarroceriaSecundario` ASC) VISIBLE,
  INDEX `FK_ColoresXA-Ter_idx` (`colorCarroceriaTerciario` ASC) VISIBLE,
  INDEX `FK_ColoesXA-Base_idx` (`colorBase` ASC) VISIBLE,
  INDEX `FK_ColoesXA-Inter_idx` (`colorInteriores` ASC) VISIBLE,
  INDEX `FK_ColoesXA-Vidrios_idx` (`colorVidrios` ASC) VISIBLE,
  CONSTRAINT `FK_ColoresXA-Principal`
    FOREIGN KEY (`colorCarroceriaPrincipal`)
    REFERENCES `virtuajoint`.`Colores` (`idColores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ColoresXA-Sec`
    FOREIGN KEY (`colorCarroceriaSecundario`)
    REFERENCES `virtuajoint`.`Colores` (`idColores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ColoresXA-Ter`
    FOREIGN KEY (`colorCarroceriaTerciario`)
    REFERENCES `virtuajoint`.`Colores` (`idColores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ColoesXA-Base`
    FOREIGN KEY (`colorBase`)
    REFERENCES `virtuajoint`.`Colores` (`idColores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ColoesXA-Inter`
    FOREIGN KEY (`colorInteriores`)
    REFERENCES `virtuajoint`.`Colores` (`idColores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ColoesXA-Vidrios`
    FOREIGN KEY (`colorVidrios`)
    REFERENCES `virtuajoint`.`Colores` (`idColores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuajoint`.`LugaresCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuajoint`.`LugaresCompra` (
  `idlugaresCompra` INT NOT NULL AUTO_INCREMENT,
  `nombreLugarCompra` VARCHAR(45) NULL,
  PRIMARY KEY (`idlugaresCompra`),
  UNIQUE INDEX `idlugaresCompra_UNIQUE` (`idlugaresCompra` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuajoint`.`TipoMarca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuajoint`.`TipoMarca` (
  `idTipoMarca` INT NOT NULL,
  `nombreTipoMarca` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuajoint`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuajoint`.`Marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `nombreMarca` VARCHAR(45) NOT NULL,
  `idTipoMarca` INT NOT NULL,
  PRIMARY KEY (`idMarca`, `idTipoMarca`),
  UNIQUE INDEX `nombreMarca_UNIQUE` (`nombreMarca` ASC) VISIBLE,
  UNIQUE INDEX `idMarca_UNIQUE` (`idMarca` ASC) VISIBLE,
  INDEX `FK-Marca-Tipo_idx` (`idTipoMarca` ASC) VISIBLE,
  CONSTRAINT `FK-Marca-Tipo`
    FOREIGN KEY (`idTipoMarca`)
    REFERENCES `virtuajoint`.`TipoMarca` (`idTipoMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuajoint`.`Modelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuajoint`.`Modelos` (
  `idModelos` INT NOT NULL AUTO_INCREMENT,
  `nombreModelo` VARCHAR(45) NOT NULL,
  `añoModelo` VARCHAR(45) NULL,
  `idMarcaJuguetera` INT NOT NULL,
  `idMarcarArmadora` INT NOT NULL,
  PRIMARY KEY (`idModelos`, `idMarcaJuguetera`, `idMarcarArmadora`),
  UNIQUE INDEX `idModelos_UNIQUE` (`idModelos` ASC) VISIBLE,
  INDEX `FK_Modelos-Armadoras_idx` (`idMarcarArmadora` ASC) VISIBLE,
  CONSTRAINT `FK_Modelos-Armadoras`
    FOREIGN KEY (`idMarcarArmadora`)
    REFERENCES `virtuajoint`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Modelos-Jugueteras`
    FOREIGN KEY (`idMarcaJuguetera`)
    REFERENCES `virtuajoint`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuajoint`.`Autos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuajoint`.`Autos` (
  `idAutos` INT NOT NULL AUTO_INCREMENT,
  `fechaCompra` DATE NOT NULL DEFAULT '1990-02-19',
  `precioCompra` DECIMAL(5,2) NOT NULL DEFAULT 0.0,
  `idLugarCompra` INT NOT NULL,
  `idModeloAuto` INT NOT NULL,
  `idColoresXAuto` INT NOT NULL,
  PRIMARY KEY (`idAutos`, `idLugarCompra`, `idModeloAuto`, `idColoresXAuto`),
  UNIQUE INDEX `idAutos_UNIQUE` (`idAutos` ASC) VISIBLE,
  INDEX `FK_Autos-Lugar_idx` (`idLugarCompra` ASC) VISIBLE,
  INDEX `FK_Autos-Modelo_idx` (`idModeloAuto` ASC) VISIBLE,
  UNIQUE INDEX `idColoresXAuto_UNIQUE` (`idColoresXAuto` ASC) VISIBLE,
  CONSTRAINT `FK_Autos-Lugar`
    FOREIGN KEY (`idLugarCompra`)
    REFERENCES `virtuajoint`.`LugaresCompra` (`idlugaresCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Autos-Modelo`
    FOREIGN KEY (`idModeloAuto`)
    REFERENCES `virtuajoint`.`Modelos` (`idModelos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Autos-ColorXA`
    FOREIGN KEY (`idColoresXAuto`)
    REFERENCES `virtuajoint`.`ColoresPorAuto` (`idColoresPorAuto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
