INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (1,'934.5',2016,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (2,'2 Jet Z',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (3,'240 Drift Wagon',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (4,'356B Convertible',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (5,'370Z',2010,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (6,'5 Alarm',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (7,'599XX',2009,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (8,'718 Boxster',2016,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (9,'8C Competizione',2007,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (10,'911 GT-2',2010,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (11,'911 Rally',1985,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (12,'917LH',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (13,'918 Spyder',2013,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (14,'Acre Maker',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (15,'Airuption',2022,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (16,'Alpine A110',2017,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (17,'AMG GT',2014,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (18,'Aristo Rat',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (19,'Aventador J',2012,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (20,'Baja Bandit',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (21,'Baja Bone Shaker',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (22,'Ballistik',2002,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (23,'Barracuda Formula S',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (24,'Beat All',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (25,'Bel Air',1957,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (26,'Bentayga',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (27,'Blastous Moto',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (28,'Bogzilla',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (29,'Bot Wheels',2018,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (30,'Bricking Speed',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (31,'Bricking Trails',2022,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (32,'Bronco',2021,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (33,'Bump Around',2017,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (34,'C4 Cactus',2018,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (35,'Camaro',1981,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (36,'Camaro Custom',2011,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (37,'Camaro SS',2016,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (38,'Carbonator',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (39,'Carrera GT',2003,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (40,'Charger',1969,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (41,'Charger',1971,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (42,'Chevelle SS 396',1967,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (43,'Chevy Nova',1966,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (44,'Chiron',2016,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (45,'Chow Mobile',2014,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (46,'City Turbo II',1985,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (47,'Civic Custom',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (48,'Civic EF',1990,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (49,'Classic 55 Nomad',1955,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (50,'Clear Speeder',2021,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (51,'Cliff Hanger',2010,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (52,'Cloud Cutter',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (53,'Cobra 427 S/C',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (54,'Colorado Xtreme',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (55,'Continental',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (56,'Corvette',1955,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (57,'Corvette C6R',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (58,'Corvette C7 Z06',2016,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (59,'Corvette C7 Z06 Convertible',2017,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (60,'Corvette C7.R',2014,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (61,'Corvette Gasser',1962,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (62,'Corvette Racer',1969,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (63,'Corvette Stingray',2014,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (64,'Cosmic Coupe',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (65,'Count Muscula',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (66,'Crop Master',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (67,'CR-X',1985,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (68,'CR-X',1988,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (69,'CTS Coupe',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (70,'Custom Mustang GT',2018,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (71,'Custom Datsun 240Z',1973,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (72,'Custom Small Block',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (73,'CX-5',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (74,'Cybertruck',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (75,'Darth Vader',2014,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (76,'DAVancenator',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (77,'DB10',2014,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (78,'DB5',1963,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (79,'DBS',2010,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (80,'Deora III',2018,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (81,'Diaper Dragger',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (82,'Dimachinni Veloce',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (83,'Dino 246 GTS',1968,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (84,'Draggin Tail',2009,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (85,'Dragster',1994,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (86,'Dune Crusher',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (87,'Dune-A-Soar',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (88,'Eevil Weevil',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (89,'El Camino 71',1971,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (90,'Electro Silhouette',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (91,'Escort RS1600',1970,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (92,'Esprit S1',1976,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (93,'Express Delivery',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (94,'F1',1992,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (95,'F1 GT3',1995,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (96,'F1 GTR',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (97,'F-100',1956,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (98,'F-150 SVT Raptor',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (99,'Firebird',1970,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (100,'Firebird',1984,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (101,'Four X Force',2015,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (102,'F-Type',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (103,'Geoterra',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (104,'GLE Coupe',2015,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (105,'Glory Chaser',2022,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (106,'GT LM',2005,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (107,'GTO',2006,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (108,'GT-R (R35) - Guaczilla',2017,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (109,'GTR R35',2017,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (110,'Haulin Class',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (111,'Haul-O-Gram',2019,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (112,'Head Gasket',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (113,'Honda CR-X',1988,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (114,'Hot Wired',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (115,'HotWheels Transit Connect',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (116,'Huayra',2012,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (117,'Huracan LP 610-4',2014,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (118,'Hyper Rocker',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (119,'Indy 500 Oval',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (120,'Iridium',2014,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (121,'Jay Leno Tank Car',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (122,'Justice League Batmobile',2017,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (123,'Kadett',1975,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (124,'Kanan',2014,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (125,'Knight Draggin',2020,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (126,'L200 Triton',2008,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (127,'Land Rover Defender 110',1997,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (128,'Land Shark',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (129,'LB Super Silhouette Silvia (S15)',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (130,'LB-Silhouette WORKS GT 35GT-RR VER.2',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (131,'Lets Go',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (132,'Lightnin Bug',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (133,'LM002',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (134,'Load Lifter',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (135,'Luke Skywalker',2014,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (136,'Mario Standard Kart',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (137,'Matt and Debbie Hays Pro Street Thunderbird',1988,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (138,'MBX 4X4',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (139,'MBX Armored Truck',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (140,'MBX Mini Swisher',2018,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (141,'Meter Made',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (142,'MGB Coupe',1971,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (143,'MGB GT Coupe',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (144,'Mini Cooper',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (145,'Model 3',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (146,'Model S',2012,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (147,'MR2',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (148,'Mustang',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (149,'Mustang 2+2 Fastback',1965,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (150,'Mustang Convertible',2018,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (151,'Mustang GT',2018,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (152,'Mustang GT Concept',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (153,'Mustang Mach-E 1400',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (154,'MX-5 Miata',2015,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (155,'MX-5 Miata',1991,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (156,'MXR',2013,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (157,'NSX Concept',2012,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (158,'Octane',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (159,'Off Road Rider',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (160,'Ollie Rocket',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (161,'P1',2013,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (162,'Pajero Evolution',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (163,'Panamera',2013,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (164,'Panamera Turbo S E-Hybrid Spor Turismo',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (165,'PickUp',1940,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (166,'Piranha Terror',2019,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (167,'Power Pistons',1994,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (168,'Push N Puller',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (169,'Quarry King',2007,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (170,'R390 GT1',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (171,'R8',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (172,'Rally Truck',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (173,'Range Rover Classic',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (174,'Range Rover Evoque',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (175,'Ranger Raptor',2019,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (176,'Rat Rig',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (177,'RD-03',2014,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (178,'Red Planet Transport',2021,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (179,'Reventon Roadster',2007,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (180,'Rising Heat',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (181,'Road Mauler',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (182,'Roller Toaster',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (183,'RS 6 Avant',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (184,'RS2 Avant',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (186,'RX-7',1995,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (187,'RZR',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (188,'S2000',2011,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (189,'Savanna RX-7 FC3S',1989,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (190,'SC400',1990,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (191,'Sea Hunter',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (192,'Series III PickUp',1971,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (193,'Sesto Elemento',2010,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (194,'Shelby GT500',2010,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (195,'Silverado Trail Boss LT',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (196,'Skidster',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (197,'Skull Shaker',2019,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (198,'Skull Shaker',2018,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (199,'Skyline 2000 GT-R',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (200,'Skyline 2000 GTX',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (201,'Skyline GT-R (BNR32)',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (202,'Slingshot',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (203,'SLS',2010,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (204,'Snow Ripper',2016,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (205,'Snow Stormer',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (206,'Sooo Fast',2000,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (207,'SP2',1972,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (208,'Spark Arrestor',2014,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (209,'Speed Trap',2020,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (210,'Sport Quattro',1984,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (211,'Sport RS',2010,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (212,'Street Wiener',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (213,'Swamp Commander',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (214,'Swat Truck',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (215,'Sweet Driver',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (216,'Sweptside Pickup',1957,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (217,'Symbolic',2020,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (218,'Terrain Trouncer',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (219,'Terzo Millennio',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (220,'TGS Dump truck 18.440',2018,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (221,'The Dark Knight Batmobile',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (222,'Tomb Up',2019,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (223,'Turbine Sublime',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (224,'V12 Speedster',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (225,'V60',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (226,'Valhalla Concept',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (227,'Van',1986,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (228,'Vantom',2012,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (229,'Veloci-Racer',1901,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (230,'Viper RT/10',1992,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (231,'Vulcan',2015,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (232,'What-4-2',2020,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (233,'Wicket',2014,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (234,'Willys Pickup 4x4',1962,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (235,'Wrangler',2017,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (236,'WRX STI',2015,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (237,'XE SV Project 8',2017,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (238,'XJ220',1992,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (239,'X-Wing Fighter',2016,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (240,'Yoda',2014,0,0);
INSERT INTO `virtuajoint`.`Modelos` (`idModelos`, `nombreModelo`, `añoModelo`, `idMarcaJuguetera`, `idMarcarArmadora`) VALUES (241,'Z Proto',1901,0,0);
