INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (1,'Aurrera Esmeralda San Alfonso');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (2,'Aurrera La Viga');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (3,'Aurrera Matilde, Pachuca');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (4,'Aurrera Viaducto');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (5,'Beto Superwheels');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (6,'Chedraui Universidad');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (7,'Comercial Mexicana Chabacano');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (8,'Coppel Viaducto');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (9,'Desconocido');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (10,'Jamaica');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (11,'Juguetibici Las Antenas');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (12,'Leobas Shop');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (13,'Liverpool Parque Delta');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (14,'Liverpool Santa Fé');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (15,'Mega Soriana Asturias');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (16,'Mega Soriana Coapa');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (17,'Mercado Ortíz Tirado');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (18,'Papeleria Veracruz');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (19,'Puesto de Coyuya');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (20,'Puesto de Francisco Daniel en Coruña');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (21,'Puesto de Insurgentes');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (22,'Puesto de Jamaica');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (23,'Regalo de Jeannette');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (24,'Soriana Asturias');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (25,'Soriana Coapa');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (26,'Soriana El Retoño');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (27,'Soriana Parque Delta');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (28,'Tianguis Juguetes Alameda');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (29,'Walmart Azcapotzalco');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (30,'Walmart Boturini');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (31,'Walmart miramontes');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (32,'Walmart Miramontes');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (33,'Walmart Nativitas');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (34,'Walmart Periferico Sur');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (35,'Walmart Portal Centro');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (36,'Walmart Taxqueña');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (37,'Walmart Universidad');
INSERT INTO `virtuajoint`.`LugaresCompra` (`idlugaresCompra`, `nombreLugarCompra`) VALUES (38,'Walmart Villacoapa');
